### ISSUE TITLE
[Bug] Syntax highlighting issues

### ISSUE THREAD

**Issue by sancarn** [SSlinky/VBA-LanguageServer#5]
**Describe the bug**

Not sure if this is singular to me, but there are numerous syntax highlighting issues 

![image](https://github.com/SSlinky/VBA-LanguageServer/assets/7938900/b734dd9d-7147-45eb-81bb-2ca68defecf3)

![image](https://github.com/SSlinky/VBA-LanguageServer/assets/7938900/76e750f6-b685-463f-ad46-49a192dd74eb)

`Set` looks incorrect - usually is dark blue, but unsure how this should be defined.

![image](https://github.com/SSlinky/VBA-LanguageServer/assets/7938900/06dc2903-d013-4457-b5f6-f150cb87a2ae)

If okay but sometimes not:

![image](https://github.com/SSlinky/VBA-LanguageServer/assets/7938900/78890e1d-16d0-4ded-a23c-48c98a1ea330)

**To Reproduce**

Load [stdAcc](https://github.com/sancarn/stdVBA/blob/master/src/stdAcc.cls)

**Comment by sancarn** [comment]
More issues:

![image](https://github.com/SSlinky/VBA-LanguageServer/assets/7938900/b021d985-6688-496a-b4b4-bab3e9476459)

**Comment by SSlinky** [comment]
I've fixed the `Set` issue but I'll have to come back to the others. The `On Error` one is really weird. It works wherever you put that line except where it is!

**Comment by sancarn** [comment]
>  The `On Error` one is really weird. It works wherever you put that line except where it is!

That sounds incredibly bizarre...

**Comment by SSlinky** [comment]
Commit de4c923 addresses the `On Error` issue. Have published a patch version.

**Comment by SSlinky** [comment]
> Commit [de4c923](https://github.com/SSlinky/VBA-LanguageServer/commit/de4c923bf539a5ff03a2cad7a9268b86de69f6f9) addresses the `On Error` issue. Have published a patch version.

"Addresses" is perhaps too strong. Looks like it's something to do with If statements completely breaking a method.

**Comment by SSlinky** [comment]
![image](https://github.com/SSlinky/VBA-LanguageServer/assets/39886505/714ac816-a130-47b9-9b1a-8f671e8f8fa8)

Have addressed some issues with syntax in 3732004. This is what happens when you take nine months off a project. You forget there were issues with it! I've also made some significant improvements to performance. Your stdAcc was killing it, so I've programmed it not to attempt to parse it at all.

I kid. Sort of. I added a 1 second delay to kicking off the parser. If another onDocumentChange is received, it doesn't do anything. So only the most recent request - assuming no changes in second - is processed.

If you switch to the pre-release version, you should see these changes. Enough for tonight. Nearly 3am.

**Comment by sancarn** [comment]
FYI, Set keyword in this code is not highlighted.

```vb
  With This.Factory
    Set .OnInit = OnInit
    Set .OnDestroy = OnDestroy
  End With
```

I imagine it would be a good idea to use @Beakerboy 's [antlr grammar](https://github.com/Beakerboy/grammars-v4/blob/master/vba/vba.g4) as it contains a number of fixes including this one.

**Comment by Beakerboy** [comment]
The dev ANTLR grammer has a lot of improvements over the one in the main ANTLR repository. I need to actually submit it to the organization for inclusion as a new VBA7 grammer. The existing one is supposed to only be VBA6.

**Comment by SSlinky** [comment]
> I imagine it would be a good idea to use @Beakerboy 's [antlr grammar](https://github.com/Beakerboy/grammars-v4/blob/master/vba/vba.g4)

Not a bad suggestion. I've made some changes on the original to make things easier to resolve in the server, but not a whole lot. This particular `Set` issue is the Textmate grammar though.
